### ISSUE TITLE
Does this only work with DE?

### ISSUE THREAD

**Issue by DragonWario** [3096/furnace#1]
I tried using this with XC2 but I ended up with "runtime error: index out of range [1] with length 1". 

The test ran fine but I don't think pc079404 is a model from 2, so I'd assume this tool may need model data only used in DE?

**Comment by 3096** [comment]
which model did you try to edit?

**Comment by DragonWario** [comment]
np020002, one of the event models for Mythra.

**Comment by DragonWario** [comment]
bump

**Comment by DragonWario** [comment]
Bump

**Comment by DragonWario** [comment]
bump

**Comment by DragonWario** [comment]
bump

**Comment by DragonWario** [comment]
bump

**Comment by DragonWario** [comment]
bump

**Comment by DragonWario** [comment]
bump

**Comment by DragonWario** [comment]
bump

**Comment by DragonWario** [comment]
Bump

**Comment by DragonWario** [comment]
bump

**Comment by DragonWario** [comment]
I've been able to confirm this works on normal models from XC2, however event models that I tried are not compatible.
